services:
  - type: web
    name: shareview-backend
    runtime: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    plan: free
    env: docker
    region: singapore
    healthCheckPath: /actuator/health
    autoDeploy: true
    envVars:
      - key: PORT
        value: 8080
      - key: MYSQL_URL
        fromDatabase:
          name: shareview-mysql
          property: url
      - key: MYSQL_USERNAME
        fromDatabase:
          name: shareview-mysql
          property: username
      - key: MYSQL_PASSWORD
        fromDatabase:
          name: shareview-mysql
          property: password
      - key: GMAIL_USERNAME
        sync: false
      - key: GMAIL_PASSWORD
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false