services:
  - type: web
    name: shareview-backend
    runtime: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    plan: free
    env: docker
    region: singapore
    autoDeploy: true
    envVars:
      - key: PORT
        value: 8080
      # MySQL Database Variables (YOUR NAMES)
      - key: SPRING_DATABASE_URL
        fromDatabase:
          name: shareview-mysql
          property: url
      - key: SPRING_DATABASE_USERNAME
        fromDatabase:
          name: shareview-mysql
          property: username
      - key: SPRING_DATABASE_PASSWORD
        fromDatabase:
          name: shareview-mysql
          property: password
      # Email Variables (YOUR NAMES)
      - key: USER_EMAIL
        sync: false
      - key: USER_PASS
        sync: false
      # Cloudinary Variables (YOUR NAMES)
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false